[window]
opacity = 0.9

  [window.dimensions]
  columns = 100
  lines = 60

  [window.padding]
  x = 4
  y = 4

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 14

  [font.normal]
  family = "monospace"
  style = "Regular"

  [font.bold]
  family = "monospace"
  style = "Bold"

  [font.offset]
  x = 1
  y = 1

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Insert"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
